-- başına ** koyarsan başlık oluyor

kurallar = {
    "**BILGINIZE,",
"Yetkililere uyulmak zorundasın, yetkiliyle bir sıkıntın varsa onun üstlerine bildir.",
"!sk komutuyla yetkili çağırabilirsin.",
	"**Genel Kurallar",
"Sunucu içerisinde troll, küfür, ırkçı söylemlerde bulunmak kesinlikle yasaktır.",
"Profesörlere saygılı olunmalıdır.",
"Ders verilen sınıfta, sınıfın huzurunu bozmak ve RP'yi bozacak cümleler kurmak yasaktır.",
"Okul içinde büyü atmak yasaktır.",
"Derslere geç kalındığında, profesörlere sınıfa alması için yalvarmak veya ısrar etmek yasaktır.",
"Derslerde anlatılan konu ile alakasız soru sormak,işlenilen dersin akışını bozmak yasaktır.",
"Derste Parmak Kaldırmadan söz almak yasaktır.",
"İçinde bulunduğunuz karakterlerin ruh halini ve psikolojik yapısını bilmeden rolünü yapamazsınız.",
"Okulda Affedilmez Lanetler kullanılması kesinlikle yasaktır.",
"Okul içerisinde Profesörlere ne zaman büyü alıcaz veya ne zaman ders açılacak gibi sorular sormayın.",
"Ders esnasında kazandığınız büyüleri gereksiz yere kullanmayınız.",
"Oyuncuları rahatsız etmek,istemedikleri role zorlamak,PM yolu ile rahatsız etmek yasaktır.",
"Snatcher'lar bir kişiyi kaçırdıktan sonra o kişiyi 5 dakika tutabilir. Ayrıca kaçırma işlemi 5 dakikada bir olur.",
"Kurt Adamlar okula giremez.",
"Karanlık tarafın işkence süresi 5 dakikadır.",
"Seherbazlar Affedilmez Lanet'i en son çare olarak kullanabilir. (Her rol için geçerli.)",
"Karanlık Taraf sunucuda her hangi bir yönetici yok iken saldırı yapamaz.",
"NLR süresi 5 dakikadır.",
"AFK kişiler kaçırılamaz.",
"Düello yapmak için profesörlerden izin almanız gerekmektedir.",
"Düelloda yanıcı, patlayıcı veya ölümcül herhangi bir büyü kullanılması yasaktır.",
"Düello'da rakibi aşağılayıcı sözlerin söylenmesi yasaktır.",
"Genel düello kurallarına uyunuz.",
"Öğrenci iken kesinlikle affedilmez lanet kullanılmamalıdır.",
"Derslerde profesörlerin kurallarına uyulmalıdır.",
"Disiplinli bir öğrenci olunmalıdır.",
"Bölümünün özelliğine göre bir öğrenci olunmalıdır.",
"Profesörlere karşı gelmeniz kesinlikle yasaktır.",
"Sunucuda her hangi bir açığı kasıtlı olarak kullanmanız yasaktır.",
"İsminizde küfür geçmemelidir.",
}